package harshal.temkar.apidocgen.model.dto;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Business logic documentation generated by AI.
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BusinessLogicDoc {

	private String summary;
	private String purpose;
	private List<String> businessRules;
	private List<String> validations;
	private List<String> dataTransformations;
	private String expectedBehavior;
	private List<String> errorScenarios;
}