package harshal.temkar.apidocgen.model.dto;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Technical workflow documentation generated by AI.
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TechnicalWorkflowDoc {

	private String workflowSummary;
	private List<WorkflowStep> steps;
	private List<String> serviceDependencies;
	private List<String> databaseOperations;
	private List<String> externalApiCalls;
	private String transactionBoundary;
	private List<String> performanceConsiderations;

	@Data
	@Builder
	@NoArgsConstructor
	@AllArgsConstructor
	public static class WorkflowStep {
		private int stepNumber;
		private String description;
		private String componentInvolved;
		private String action;
	}
}